// Mocks generated by Mockito 5.4.6 from annotations
// in pft/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pft/core/services/exercise_seed_service.dart' as _i5;
import 'package:pft/domain/entities/exercise.dart' as _i2;
import 'package:pft/domain/entities/exercise_enums.dart' as _i13;
import 'package:pft/domain/entities/workout.dart' as _i3;
import 'package:pft/domain/repositories/exercise_repository.dart' as _i4;
import 'package:pft/domain/repositories/workout_repository.dart' as _i6;
import 'package:pft/domain/usecases/create_custom_exercise.dart' as _i10;
import 'package:pft/domain/usecases/create_workout.dart' as _i15;
import 'package:pft/domain/usecases/delete_workout.dart' as _i17;
import 'package:pft/domain/usecases/get_exercises.dart' as _i9;
import 'package:pft/domain/usecases/get_workouts.dart' as _i14;
import 'package:pft/domain/usecases/search_exercises.dart' as _i12;
import 'package:pft/domain/usecases/seed_exercises.dart' as _i11;
import 'package:pft/domain/usecases/update_workout.dart' as _i16;
import 'package:uuid/uuid.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExercise_0 extends _i1.SmartFake implements _i2.Exercise {
  _FakeExercise_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWorkout_1 extends _i1.SmartFake implements _i3.Workout {
  _FakeWorkout_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExerciseRepository_2 extends _i1.SmartFake
    implements _i4.ExerciseRepository {
  _FakeExerciseRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExerciseSeedService_3 extends _i1.SmartFake
    implements _i5.ExerciseSeedService {
  _FakeExerciseSeedService_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWorkoutRepository_4 extends _i1.SmartFake
    implements _i6.WorkoutRepository {
  _FakeWorkoutRepository_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUuid_5 extends _i1.SmartFake implements _i7.Uuid {
  _FakeUuid_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExerciseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseRepository extends _i1.Mock
    implements _i4.ExerciseRepository {
  MockExerciseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i2.Exercise>> getExercises() => (super.noSuchMethod(
        Invocation.method(
          #getExercises,
          [],
        ),
        returnValue: _i8.Future<List<_i2.Exercise>>.value(<_i2.Exercise>[]),
      ) as _i8.Future<List<_i2.Exercise>>);

  @override
  _i8.Future<_i2.Exercise?> getExerciseById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getExerciseById,
          [id],
        ),
        returnValue: _i8.Future<_i2.Exercise?>.value(),
      ) as _i8.Future<_i2.Exercise?>);

  @override
  _i8.Future<_i2.Exercise> createExercise(_i2.Exercise? exercise) =>
      (super.noSuchMethod(
        Invocation.method(
          #createExercise,
          [exercise],
        ),
        returnValue: _i8.Future<_i2.Exercise>.value(_FakeExercise_0(
          this,
          Invocation.method(
            #createExercise,
            [exercise],
          ),
        )),
      ) as _i8.Future<_i2.Exercise>);

  @override
  _i8.Future<void> deleteExercise(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteExercise,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> seedExercises(List<_i2.Exercise>? exercises) =>
      (super.noSuchMethod(
        Invocation.method(
          #seedExercises,
          [exercises],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> hasExercises() => (super.noSuchMethod(
        Invocation.method(
          #hasExercises,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);
}

/// A class which mocks [WorkoutRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutRepository extends _i1.Mock implements _i6.WorkoutRepository {
  MockWorkoutRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i3.Workout>> getWorkouts() => (super.noSuchMethod(
        Invocation.method(
          #getWorkouts,
          [],
        ),
        returnValue: _i8.Future<List<_i3.Workout>>.value(<_i3.Workout>[]),
      ) as _i8.Future<List<_i3.Workout>>);

  @override
  _i8.Future<_i3.Workout?> getWorkoutById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getWorkoutById,
          [id],
        ),
        returnValue: _i8.Future<_i3.Workout?>.value(),
      ) as _i8.Future<_i3.Workout?>);

  @override
  _i8.Future<_i3.Workout> createWorkout(_i3.Workout? workout) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWorkout,
          [workout],
        ),
        returnValue: _i8.Future<_i3.Workout>.value(_FakeWorkout_1(
          this,
          Invocation.method(
            #createWorkout,
            [workout],
          ),
        )),
      ) as _i8.Future<_i3.Workout>);

  @override
  _i8.Future<_i3.Workout> updateWorkout(_i3.Workout? workout) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWorkout,
          [workout],
        ),
        returnValue: _i8.Future<_i3.Workout>.value(_FakeWorkout_1(
          this,
          Invocation.method(
            #updateWorkout,
            [workout],
          ),
        )),
      ) as _i8.Future<_i3.Workout>);

  @override
  _i8.Future<void> deleteWorkout(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteWorkout,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i3.Workout>> getTemplates() => (super.noSuchMethod(
        Invocation.method(
          #getTemplates,
          [],
        ),
        returnValue: _i8.Future<List<_i3.Workout>>.value(<_i3.Workout>[]),
      ) as _i8.Future<List<_i3.Workout>>);
}

/// A class which mocks [GetExercises].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetExercises extends _i1.Mock implements _i9.GetExercises {
  MockGetExercises() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ExerciseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeExerciseRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.ExerciseRepository);

  @override
  _i8.Future<List<_i2.Exercise>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i8.Future<List<_i2.Exercise>>.value(<_i2.Exercise>[]),
      ) as _i8.Future<List<_i2.Exercise>>);
}

/// A class which mocks [CreateCustomExercise].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateCustomExercise extends _i1.Mock
    implements _i10.CreateCustomExercise {
  MockCreateCustomExercise() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ExerciseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeExerciseRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.ExerciseRepository);

  @override
  _i8.Future<_i2.Exercise> call({
    required String? name,
    required String? muscleGroup,
    required String? category,
    required String? equipmentType,
    String? instructions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #name: name,
            #muscleGroup: muscleGroup,
            #category: category,
            #equipmentType: equipmentType,
            #instructions: instructions,
          },
        ),
        returnValue: _i8.Future<_i2.Exercise>.value(_FakeExercise_0(
          this,
          Invocation.method(
            #call,
            [],
            {
              #name: name,
              #muscleGroup: muscleGroup,
              #category: category,
              #equipmentType: equipmentType,
              #instructions: instructions,
            },
          ),
        )),
      ) as _i8.Future<_i2.Exercise>);
}

/// A class which mocks [SeedExercises].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeedExercises extends _i1.Mock implements _i11.SeedExercises {
  MockSeedExercises() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ExerciseSeedService get seedService => (super.noSuchMethod(
        Invocation.getter(#seedService),
        returnValue: _FakeExerciseSeedService_3(
          this,
          Invocation.getter(#seedService),
        ),
      ) as _i5.ExerciseSeedService);

  @override
  _i8.Future<void> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [SearchExercises].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchExercises extends _i1.Mock implements _i12.SearchExercises {
  MockSearchExercises() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ExerciseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeExerciseRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.ExerciseRepository);

  @override
  _i8.Future<List<_i2.Exercise>> call({
    String? query,
    Set<_i13.MuscleGroup>? muscleGroups,
    Set<_i13.ExerciseCategory>? categories,
    Set<_i13.EquipmentType>? equipmentTypes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #query: query,
            #muscleGroups: muscleGroups,
            #categories: categories,
            #equipmentTypes: equipmentTypes,
          },
        ),
        returnValue: _i8.Future<List<_i2.Exercise>>.value(<_i2.Exercise>[]),
      ) as _i8.Future<List<_i2.Exercise>>);
}

/// A class which mocks [GetWorkouts].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWorkouts extends _i1.Mock implements _i14.GetWorkouts {
  MockGetWorkouts() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.WorkoutRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeWorkoutRepository_4(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i6.WorkoutRepository);

  @override
  _i8.Future<List<_i3.Workout>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i8.Future<List<_i3.Workout>>.value(<_i3.Workout>[]),
      ) as _i8.Future<List<_i3.Workout>>);
}

/// A class which mocks [CreateWorkout].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateWorkout extends _i1.Mock implements _i15.CreateWorkout {
  MockCreateWorkout() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.WorkoutRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeWorkoutRepository_4(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i6.WorkoutRepository);

  @override
  _i7.Uuid get uuid => (super.noSuchMethod(
        Invocation.getter(#uuid),
        returnValue: _FakeUuid_5(
          this,
          Invocation.getter(#uuid),
        ),
      ) as _i7.Uuid);

  @override
  _i8.Future<_i3.Workout> call(_i3.Workout? workout) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [workout],
        ),
        returnValue: _i8.Future<_i3.Workout>.value(_FakeWorkout_1(
          this,
          Invocation.method(
            #call,
            [workout],
          ),
        )),
      ) as _i8.Future<_i3.Workout>);
}

/// A class which mocks [UpdateWorkout].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateWorkout extends _i1.Mock implements _i16.UpdateWorkout {
  MockUpdateWorkout() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.WorkoutRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeWorkoutRepository_4(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i6.WorkoutRepository);

  @override
  _i8.Future<_i3.Workout> call(_i3.Workout? workout) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [workout],
        ),
        returnValue: _i8.Future<_i3.Workout>.value(_FakeWorkout_1(
          this,
          Invocation.method(
            #call,
            [workout],
          ),
        )),
      ) as _i8.Future<_i3.Workout>);
}

/// A class which mocks [DeleteWorkout].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteWorkout extends _i1.Mock implements _i17.DeleteWorkout {
  MockDeleteWorkout() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.WorkoutRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeWorkoutRepository_4(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i6.WorkoutRepository);

  @override
  _i8.Future<void> call(String? workoutId) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [workoutId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}
