// Mocks generated by Mockito 5.4.6 from annotations
// in pft/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pft/core/services/exercise_seed_service.dart' as _i4;
import 'package:pft/domain/entities/exercise.dart' as _i2;
import 'package:pft/domain/entities/exercise_enums.dart' as _i10;
import 'package:pft/domain/repositories/exercise_repository.dart' as _i3;
import 'package:pft/domain/usecases/create_custom_exercise.dart' as _i7;
import 'package:pft/domain/usecases/get_exercises.dart' as _i6;
import 'package:pft/domain/usecases/search_exercises.dart' as _i9;
import 'package:pft/domain/usecases/seed_exercises.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExercise_0 extends _i1.SmartFake implements _i2.Exercise {
  _FakeExercise_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExerciseRepository_1 extends _i1.SmartFake
    implements _i3.ExerciseRepository {
  _FakeExerciseRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExerciseSeedService_2 extends _i1.SmartFake
    implements _i4.ExerciseSeedService {
  _FakeExerciseSeedService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExerciseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseRepository extends _i1.Mock
    implements _i3.ExerciseRepository {
  MockExerciseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.Exercise>> getExercises() => (super.noSuchMethod(
        Invocation.method(
          #getExercises,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Exercise>>.value(<_i2.Exercise>[]),
      ) as _i5.Future<List<_i2.Exercise>>);

  @override
  _i5.Future<_i2.Exercise?> getExerciseById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getExerciseById,
          [id],
        ),
        returnValue: _i5.Future<_i2.Exercise?>.value(),
      ) as _i5.Future<_i2.Exercise?>);

  @override
  _i5.Future<_i2.Exercise> createExercise(_i2.Exercise? exercise) =>
      (super.noSuchMethod(
        Invocation.method(
          #createExercise,
          [exercise],
        ),
        returnValue: _i5.Future<_i2.Exercise>.value(_FakeExercise_0(
          this,
          Invocation.method(
            #createExercise,
            [exercise],
          ),
        )),
      ) as _i5.Future<_i2.Exercise>);

  @override
  _i5.Future<void> deleteExercise(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteExercise,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> seedExercises(List<_i2.Exercise>? exercises) =>
      (super.noSuchMethod(
        Invocation.method(
          #seedExercises,
          [exercises],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> hasExercises() => (super.noSuchMethod(
        Invocation.method(
          #hasExercises,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [GetExercises].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetExercises extends _i1.Mock implements _i6.GetExercises {
  MockGetExercises() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ExerciseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeExerciseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.ExerciseRepository);

  @override
  _i5.Future<List<_i2.Exercise>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Exercise>>.value(<_i2.Exercise>[]),
      ) as _i5.Future<List<_i2.Exercise>>);
}

/// A class which mocks [CreateCustomExercise].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateCustomExercise extends _i1.Mock
    implements _i7.CreateCustomExercise {
  MockCreateCustomExercise() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ExerciseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeExerciseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.ExerciseRepository);

  @override
  _i5.Future<_i2.Exercise> call({
    required String? name,
    required String? muscleGroup,
    required String? category,
    required String? equipmentType,
    String? instructions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #name: name,
            #muscleGroup: muscleGroup,
            #category: category,
            #equipmentType: equipmentType,
            #instructions: instructions,
          },
        ),
        returnValue: _i5.Future<_i2.Exercise>.value(_FakeExercise_0(
          this,
          Invocation.method(
            #call,
            [],
            {
              #name: name,
              #muscleGroup: muscleGroup,
              #category: category,
              #equipmentType: equipmentType,
              #instructions: instructions,
            },
          ),
        )),
      ) as _i5.Future<_i2.Exercise>);
}

/// A class which mocks [SeedExercises].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeedExercises extends _i1.Mock implements _i8.SeedExercises {
  MockSeedExercises() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ExerciseSeedService get seedService => (super.noSuchMethod(
        Invocation.getter(#seedService),
        returnValue: _FakeExerciseSeedService_2(
          this,
          Invocation.getter(#seedService),
        ),
      ) as _i4.ExerciseSeedService);

  @override
  _i5.Future<void> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [SearchExercises].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchExercises extends _i1.Mock implements _i9.SearchExercises {
  MockSearchExercises() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ExerciseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeExerciseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.ExerciseRepository);

  @override
  _i5.Future<List<_i2.Exercise>> call({
    String? query,
    Set<_i10.MuscleGroup>? muscleGroups,
    Set<_i10.ExerciseCategory>? categories,
    Set<_i10.EquipmentType>? equipmentTypes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #query: query,
            #muscleGroups: muscleGroups,
            #categories: categories,
            #equipmentTypes: equipmentTypes,
          },
        ),
        returnValue: _i5.Future<List<_i2.Exercise>>.value(<_i2.Exercise>[]),
      ) as _i5.Future<List<_i2.Exercise>>);
}
